package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	directIconSources = []string{
		"close.svg",
		"globe.svg",
		"team-indicator.svg",
	}

	slugPattern       = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*$`)
	svgViewBoxDouble  = regexp.MustCompile(`(?is)\bviewBox\s*=\s*"([^"]+)"`)
	svgViewBoxSingle  = regexp.MustCompile(`(?is)\bviewBox\s*=\s*'([^']+)'`)
	svgScriptTag      = regexp.MustCompile(`(?is)<script\b[^>]*>.*?</script>`)
	svgXMLDeclaration = regexp.MustCompile(`(?is)<\?xml\b.*?\?>`)
)

type seedLogo struct {
	Logo string `json:"logo"`
}

type spriteSource struct {
	id   string
	path string
}

func main() {
	iconsDir := flag.String("icons-dir", filepath.Join("cmd", "map", "templates", "static", "svg", "icons"), "directory containing source icon SVG files")
	seedFile := flag.String("seed", filepath.Join("pkg", "teams", "team-logos-seed.json"), "team logo seed JSON file")
	outputFile := flag.String("out", filepath.Join("cmd", "map", "templates", "static", "svg", "icons", "icons.svg"), "generated sprite SVG path")
	flag.Parse()

	sprite, err := buildSprite(*iconsDir, *seedFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate icons sprite: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outputFile, sprite, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write icons sprite: %v\n", err)
		os.Exit(1)
	}
}

func buildSprite(iconsDir, seedFile string) ([]byte, error) {
	sources, err := spriteSources(iconsDir, seedFile)
	if err != nil {
		return nil, err
	}

	var builder strings.Builder
	builder.WriteString("<!-- Generated by go run ./cmd/map/tools/generate-icons-sprite. Do not edit by hand. -->\n")
	builder.WriteString(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none">` + "\n")
	for _, source := range sources {
		symbol, err := symbolFromSVG(source.id, source.path)
		if err != nil {
			return nil, err
		}
		builder.WriteString(symbol)
		builder.WriteByte('\n')
	}
	builder.WriteString("</svg>\n")
	return []byte(builder.String()), nil
}

func spriteSources(iconsDir, seedFile string) ([]spriteSource, error) {
	sources := make([]spriteSource, 0)
	for _, filename := range directIconSources {
		slug := strings.TrimSuffix(filename, ".svg")
		if !slugPattern.MatchString(slug) {
			return nil, fmt.Errorf("invalid direct icon slug %q", slug)
		}
		sources = append(sources, spriteSource{
			id:   "icon--" + slug,
			path: filepath.Join(iconsDir, filename),
		})
	}

	seedData, err := os.ReadFile(seedFile)
	if err != nil {
		return nil, fmt.Errorf("read logo seed: %w", err)
	}

	var logos []seedLogo
	if err := json.Unmarshal(seedData, &logos); err != nil {
		return nil, fmt.Errorf("parse logo seed: %w", err)
	}

	seen := make(map[string]bool, len(logos))
	for _, logo := range logos {
		const prefix = "/static/svg/icons/badges/badge-"
		if !strings.HasPrefix(logo.Logo, prefix) || !strings.HasSuffix(logo.Logo, ".svg") {
			return nil, fmt.Errorf("unsupported seed logo path %q", logo.Logo)
		}

		slug := strings.TrimPrefix(filepath.Base(logo.Logo), "badge-")
		slug = strings.TrimSuffix(slug, ".svg")
		if !slugPattern.MatchString(slug) {
			return nil, fmt.Errorf("invalid badge slug %q", slug)
		}
		if seen[slug] {
			return nil, fmt.Errorf("duplicate badge slug %q", slug)
		}
		seen[slug] = true

		sources = append(sources, spriteSource{
			id:   "icon--badge-" + slug,
			path: filepath.Join(iconsDir, "badges", "badge-"+slug+".svg"),
		})
	}
	return sources, nil
}

func symbolFromSVG(id, path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	source := normalizeLineEndings(string(data))
	source = svgXMLDeclaration.ReplaceAllString(source, "")
	source = strings.TrimSpace(source)
	if source == "" {
		return "", fmt.Errorf("%s is empty", path)
	}

	lower := strings.ToLower(source)
	start := strings.Index(lower, "<svg")
	if start < 0 {
		return "", fmt.Errorf("%s does not contain an svg element", path)
	}
	openEndOffset := strings.Index(lower[start:], ">")
	if openEndOffset < 0 {
		return "", fmt.Errorf("%s has an incomplete svg opening tag", path)
	}
	openEnd := start + openEndOffset
	closeStart := strings.LastIndex(lower, "</svg>")
	if closeStart <= openEnd {
		return "", fmt.Errorf("%s has no closing svg element", path)
	}

	openTag := source[start : openEnd+1]
	viewBox := "0 0 64 48"
	if match := svgViewBoxDouble.FindStringSubmatch(openTag); len(match) > 1 {
		viewBox = strings.TrimSpace(match[1])
	} else if match := svgViewBoxSingle.FindStringSubmatch(openTag); len(match) > 1 {
		viewBox = strings.TrimSpace(match[1])
	}

	inner := strings.TrimSpace(source[openEnd+1 : closeStart])
	inner = strings.TrimSpace(svgScriptTag.ReplaceAllString(inner, ""))
	if inner == "" {
		return "", fmt.Errorf("%s has no drawable content", path)
	}

	return fmt.Sprintf("  <symbol id=\"%s\" viewBox=\"%s\">\n%s\n  </symbol>", id, html.EscapeString(viewBox), indent(inner, "    ")), nil
}

func normalizeLineEndings(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "\r", "\n")
	return strings.ReplaceAll(value, "\t", "  ")
}

func indent(value, prefix string) string {
	lines := strings.Split(value, "\n")
	for i, line := range lines {
		lines[i] = prefix + strings.TrimRight(line, " ")
	}
	return strings.Join(lines, "\n")
}
